//! The two generated indexes, rendered into a string.
//!
//! Both are committed files, and both are gated on being current. **Rendering returns a
//! `String`; nothing here writes.** The implementation this replaces regenerated by writing
//! the file, comparing, and writing the old bytes back — a check that mutates the tree it is
//! checking, which is why the merge check's history replay needs a discarding checkout
//! between commits. A comparison against a string needs neither.

use std::collections::{BTreeMap, BTreeSet};

use rules::{Corpus, RuleNumber};

use crate::manifest::Manifest;
use crate::model::{Document, Model};
use crate::scan::{MarkerForm, Observation};

/// How a document is named in an index.
///
/// The register is a directory of concern files, and the concern is the useful half of the
/// name — `interpretations/layers` rather than the path to it.
pub fn label(doc: &Document, interpretations_dir: &std::path::Path) -> String {
    if doc.rel.parent() == Some(interpretations_dir) {
        let stem = doc.rel.file_stem().unwrap_or_default().to_string_lossy();
        let dir = interpretations_dir
            .file_name()
            .unwrap_or_default()
            .to_string_lossy();
        return format!("{dir}/{stem}");
    }
    doc.rel.display().to_string()
}

/// Every rule the live files cite, and where, as `document · heading`.
///
/// The heading is tracked down the file, and **a heading line is applied before the rule
/// numbers on that same line**: a rule named in a heading belongs under that heading, not
/// under the one above it. The scanner emits the observations in the other order, so this
/// reorders them per line rather than replaying them as they arrive.
fn citations(model: &Model, interpretations_dir: &std::path::Path) -> BTreeMap<Sort, Vec<String>> {
    let mut out: BTreeMap<Sort, BTreeSet<String>> = BTreeMap::new();
    for doc in model.documents() {
        let name = label(doc, interpretations_dir);
        let mut heading = String::new();
        let mut by_line: BTreeMap<u32, Vec<&Observation>> = BTreeMap::new();
        for l in &doc.observations {
            by_line.entry(l.line).or_default().push(&l.what);
        }
        for (_, observations) in by_line {
            if let Some(Observation::Heading { text, .. }) = observations
                .iter()
                .find(|o| matches!(o, Observation::Heading { .. }))
                .copied()
            {
                // Everything from an em dash onwards is the statement, not the name.
                heading = text.split('—').next().unwrap_or(text).trim().to_string();
            }
            for o in observations {
                if let Observation::RuleToken(rule) = o {
                    let where_ = if heading.is_empty() {
                        name.clone()
                    } else {
                        format!("{name} · {heading}")
                    };
                    out.entry(Sort(rule.clone())).or_default().insert(where_);
                }
            }
        }
    }
    out.into_iter()
        .map(|(k, v)| (k, v.into_iter().collect()))
        .collect()
}

/// A rule number in the order the rule index is generated in: section, then the printed text.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Sort(pub RuleNumber);

impl Ord for Sort {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.0.cmp_index(&other.0)
    }
}

impl PartialOrd for Sort {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

/// `docs/rules/index.md`: every rule cited, and what depends on it.
///
/// This is what makes a bump actionable — when a rule changes or is renumbered, it says
/// exactly what has to be re-read.
pub fn rule_index(model: &Model, manifest: &Manifest, corpus: &Corpus, pinned: &str) -> String {
    let dir = manifest.interpretations().dir.clone();
    let cites = citations(model, &dir);
    let (known, unknown): (Vec<_>, Vec<_>) = cites
        .iter()
        .partition(|(Sort(rule), _)| corpus.contains(rule));

    let mut out = String::new();
    out.push_str("# Rule citation index\n\n");
    // The provenance line names the command that regenerates the file, because a generated
    // file a reader cannot regenerate is a file they will edit by hand.
    out.push_str("**Generated — do not edit.** `cargo knowledge index --write`\n\n");
    out.push_str(
        "Every Comprehensive Rule the live files cite, and where. This is what makes a\n\
         rules bump actionable: when a rule changes or is renumbered, this says exactly what\n\
         depends on it — documents today, code and tests once they exist. The survey is\n\
         excluded, being frozen against its own release.\n\n",
    );
    out.push_str(&format!(
        "Pinned rules release: `{pinned}` · {} rules cited\n\n",
        known.len()
    ));
    out.push_str("| Rule | Cites | Where |\n|---|---|---|\n");
    for (Sort(rule), where_) in &known {
        out.push_str(&format!(
            "| `{rule}` | {} | {} |\n",
            where_.len(),
            where_.join("<br>")
        ));
    }
    if !unknown.is_empty() {
        let names: Vec<String> = unknown
            .iter()
            .map(|(Sort(r), _)| format!("`{r}`"))
            .collect();
        out.push_str(&format!(
            "\n**Not rules in this release** (citation error, or prose that parses as one): {}\n",
            names.join(", ")
        ));
    }
    out
}

/// One entry of the interpretation register.
struct Entry {
    title: String,
    file: String,
    /// Every rule the entry rests on, and how it was written. `CR:` wins over `CR~` — a claim
    /// about content outranks a mention of the number.
    turns_on: BTreeMap<String, MarkerForm>,
}

/// `docs/rules/interpretations/index.md`: every entry, what it rests on, and who cites it.
///
/// It exists for what a numbering check cannot see. Uniqueness, no holes and a high-water mark
/// all describe the SHAPE of the sequence, and a replacement — delete an entry, write a
/// different reading under the same number — changes none of them. A title in a generated
/// table does change, so the diff of this file is where a lost, replaced or re-filed entry
/// becomes visible.
pub fn interpretation_index(model: &Model, manifest: &Manifest, with_lines: bool) -> String {
    let dir = manifest.interpretations().dir.clone();
    let mut entries: BTreeMap<u16, Entry> = BTreeMap::new();

    for doc in model.documents() {
        if doc.rel.parent() != Some(dir.as_path()) {
            continue;
        }
        let stem = doc.rel.file_stem().unwrap_or_default().to_string_lossy();
        if stem == "README" || stem == "index" {
            continue; // the index repeats every heading; it defines nothing
        }
        let mut current: Option<u16> = None;
        for (i, line) in doc.text.lines().enumerate() {
            if let Some((number, title)) = entry_heading(line) {
                current = Some(number);
                entries.insert(
                    number,
                    Entry {
                        title,
                        file: doc
                            .rel
                            .file_name()
                            .unwrap_or_default()
                            .to_string_lossy()
                            .into(),
                        turns_on: BTreeMap::new(),
                    },
                );
                continue;
            }
            let Some(n) = current else { continue };
            let entry = entries.get_mut(&n).expect("the heading created it");
            // A rule reaches an entry two ways and BOTH are needed. Markers carry the ones
            // named in prose; a blockquote carries its number as printed and often has no
            // marker anywhere in the entry — several entries are in that shape, where the
            // blockquoted rule is the entry's primary one.
            if let Some(rule) = blockquoted_number(line) {
                entry.turns_on.entry(rule).or_insert(MarkerForm::Prose);
            }
            for (line_no, o) in doc.observations_of(|o| match o {
                Observation::RuleMarker { number, form } if *form != MarkerForm::Identifier => {
                    Some((number.to_string(), *form))
                }
                _ => None,
            }) {
                if line_no as usize != i + 1 {
                    continue;
                }
                let (rule, form) = o;
                match entry.turns_on.get(&rule) {
                    Some(MarkerForm::Prose) => {}
                    _ => {
                        entry.turns_on.insert(rule, form);
                    }
                }
            }
        }
    }

    let cited = citing_files(model, &dir);
    render_interpretation_index(&entries, &cited, with_lines)
}

/// `R<n> — <title>` as an entry's own heading.
fn entry_heading(line: &str) -> Option<(u16, String)> {
    let rest = line.strip_prefix("## R")?;
    let (digits, tail) = rest.split_at(rest.find(|c: char| !c.is_ascii_digit())?);
    let title = tail.strip_prefix(" — ")?;
    Some((digits.parse().ok()?, title.trim_end().to_string()))
}

/// A blockquote opening with a bold rule number, as an entry's primary rule is written.
fn blockquoted_number(line: &str) -> Option<String> {
    let rest = line.strip_prefix('>')?.trim_start().strip_prefix("**")?;
    let end = rest.find("**")?;
    let token = rest[..end].strip_suffix('.').unwrap_or(&rest[..end]);
    RuleNumber::parse(token).map(|n| n.to_string())
}

/// Which live files cite each entry, and on which lines.
fn citing_files(model: &Model, dir: &std::path::Path) -> BTreeMap<u16, BTreeMap<String, Vec<u32>>> {
    let mut out: BTreeMap<u16, BTreeMap<String, Vec<u32>>> = BTreeMap::new();
    for doc in model.documents() {
        if !doc.is_markdown() {
            continue;
        }
        let inside = doc.rel.parent() == Some(dir);
        let mut per_line: BTreeMap<u32, BTreeSet<u16>> = BTreeMap::new();
        for (line, n) in doc.observations_of(|o| match o {
            Observation::InterpRef(n) => Some(*n),
            _ => None,
        }) {
            per_line.entry(line).or_default().insert(n);
        }
        for (line, numbers) in per_line {
            let text = doc.text.lines().nth(line as usize - 1).unwrap_or("");
            if inside && entry_heading(text).is_some() {
                continue; // an entry does not cite itself
            }
            for n in numbers {
                out.entry(n)
                    .or_default()
                    .entry(doc.rel.display().to_string())
                    .or_default()
                    .push(line);
            }
        }
    }
    out
}

fn render_interpretation_index(
    entries: &BTreeMap<u16, Entry>,
    cited: &BTreeMap<u16, BTreeMap<String, Vec<u32>>>,
    with_lines: bool,
) -> String {
    let mut body = Vec::new();
    for (n, entry) in entries {
        body.push(format!("## R{n} — {}\n", entry.title));
        let mut rules: Vec<&String> = entry.turns_on.keys().collect();
        rules.sort_by(|a, b| {
            let (a, b) = (RuleNumber::parse(a), RuleNumber::parse(b));
            match (a, b) {
                (Some(a), Some(b)) => a.cmp_turns(&b),
                _ => std::cmp::Ordering::Equal,
            }
        });
        let line = if rules.is_empty() {
            "Turns on: **no rule** — check this".to_string()
        } else {
            let listed: Vec<String> = rules
                .iter()
                .map(|r| {
                    let marker = match entry.turns_on[*r] {
                        MarkerForm::Mention => "CR~",
                        _ => "CR:",
                    };
                    format!("`{marker}{r}`")
                })
                .collect();
            format!("Turns on: {}", listed.join(", "))
        };
        body.push(format!("{}\n", wrap(&line, 98).join("\n")));
        let who = cited.get(n);
        match who.filter(|w| !w.is_empty()) {
            Some(files) => {
                body.push(format!(
                    "In `{}`. Cited by {} file{}:\n",
                    entry.file,
                    files.len(),
                    if files.len() > 1 { "s" } else { "" }
                ));
                for (file, lines) in files {
                    let suffix = if with_lines {
                        let plural = if lines.len() > 1 { "s" } else { "" };
                        let numbers: Vec<String> = lines.iter().map(u32::to_string).collect();
                        format!(" — line{plural} {}", numbers.join(", "))
                    } else {
                        String::new()
                    };
                    body.push(format!("- `{file}`{suffix}"));
                }
                body.push(String::new());
            }
            None => body.push(format!("In `{}`. **Cited from nowhere.**\n", entry.file)),
        }
    }

    let concerns: BTreeSet<&String> = entries.values().map(|e| &e.file).collect();
    let provenance = if with_lines {
        "**Generated — do not edit.** `cargo knowledge index --interpretations --lines`\n\n\
         **Line numbers are on, so this copy is temporary.** `cargo knowledge check` fails\n\
         while it is in the tree; regenerate without `--lines` before committing.\n\n"
    } else {
        "**Generated — do not edit.** `cargo knowledge index --interpretations --write`\n\n"
    };
    format!(
        "# Interpretation index\n\n\
         {provenance}\
         Every `R` entry, the file that holds it, and every live file that cites it. A numbering\n\
         check sees the shape of the sequence and not its content, so an entry replaced under its\n\
         own number passes every assertion; **the diff of this file is where that becomes\n\
         visible**, and `cargo knowledge check` fails if it is out of date.\n\n\
         A moved title is a replaced entry, a moved file is a re-filing, a removed section is a\n\
         loss. The citing list is the blast radius of a re-filing: every file in it names a\n\
         concern file, so moving an entry means rewriting all of them in the same change.\n\n\
         **Turns on** is every Comprehensive Rule the entry rests on, from its markers and from\n\
         the numbers its blockquotes carry as printed — `CR:` where the entry makes a claim about\n\
         the rule's content, `CR~` where it names the number only. This is the per-entry half of\n\
         a release bump: `docs/rules/index.md` says which files cite a rule, and this says which\n\
         readings would have to be re-argued if that rule moved under them.\n\n\
         The citing list is file-level, and that is what freshness is gated on: this file changes\n\
         when a citation is added, moved between files or deleted, and not when unrelated prose\n\
         shifts one down a page. `cargo knowledge index --interpretations --lines` adds the line numbers to\n\
         a temporary copy for someone who wants them; that copy fails the gate until it is\n\
         regenerated without the flag.\n\n\
         {} entries across {} concern files\n\n\
         ---\n\n{}\n",
        entries.len(),
        concerns.len(),
        body.join("\n").trim_end_matches('\n')
    )
}

/// Greedy wrap on whitespace that never breaks a word, matching the generator being replaced.
pub fn wrap(text: &str, width: usize) -> Vec<String> {
    let mut out = Vec::new();
    let mut line = String::new();
    for word in text.split_whitespace() {
        if !line.is_empty() && line.chars().count() + 1 + word.chars().count() > width {
            out.push(std::mem::take(&mut line));
        }
        if !line.is_empty() {
            line.push(' ');
        }
        line.push_str(word);
    }
    if !line.is_empty() {
        out.push(line);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn an_entry_heading_is_recognised_and_its_title_kept() {
        let (n, title) = entry_heading("## R15 — visibility rules grant").expect("a heading");
        assert_eq!(n, 15);
        assert_eq!(title, "visibility rules grant");
        assert!(entry_heading("## Rules of the game").is_none());
        assert!(entry_heading("### R15 — wrong level").is_none());
    }

    #[test]
    fn a_blockquoted_number_is_read_from_its_bold_marker() {
        // An entry's primary rule is written this way and often carries no marker anywhere.
        // Interpolated, never spelled out: a literal here is a citation of this file.
        const RULE: &str = "104.4b"; // CR~104.4b
                                     // Bound, not written into the call: a blockquote handed straight to a function is a
                                     // blockquote of this file, and the check over commentary reads it.
        const QUOTED: &str = "> **104.4b** If a game…";
        const STOPPED: &str = "> **104.4b.** With a stop";
        const PLAIN: &str = "> plain quoted text";
        let unquoted = format!("**{RULE}** not in a blockquote");
        assert_eq!(blockquoted_number(QUOTED).as_deref(), Some(RULE));
        assert_eq!(blockquoted_number(STOPPED).as_deref(), Some(RULE));
        assert!(blockquoted_number(PLAIN).is_none());
        assert!(blockquoted_number(&unquoted).is_none());
    }

    #[test]
    fn wrapping_never_breaks_a_word_and_fills_greedily() {
        assert_eq!(wrap("aaa bbb ccc", 7), vec!["aaa bbb", "ccc"]);
        assert_eq!(wrap("averylongword", 4), vec!["averylongword"]);
        assert_eq!(wrap("", 10), Vec::<String>::new());
    }
}
