//! The generated rule index, rendered into a string.
//!
//! It is a committed file, gated on being current. **Rendering returns a
//! `String`; nothing here writes.** The implementation this replaces regenerated by writing
//! the file, comparing, and writing the old bytes back — a check that mutates the tree it is
//! checking, which is why the merge check's history replay needs a discarding checkout
//! between commits. A comparison against a string needs neither.

use std::collections::{BTreeMap, BTreeSet};

use rules::{Corpus, RuleNumber};

use crate::manifest::Manifest;
use crate::model::{Document, Model};
use crate::scan::Observation;

/// How a document is named in an index: its project-relative path, whatever holds it.
///
/// One naming for every document. The shortened form the interpretation register had was a
/// second one, and it named a file the reader could not grep for.
pub fn label(doc: &Document) -> String {
    doc.rel.display().to_string()
}

/// The relative path from `dir` to `target`, the way a renderer resolves a link in a file
/// inside `dir`.
///
/// The upward segments this produces are legal here and nowhere else: both generated
/// indexes sit outside the walk, and generated text cannot go stale, which is what the
/// upward ban in hand-written links exists against.
fn rel_from(dir: &std::path::Path, target: &std::path::Path) -> std::path::PathBuf {
    let dir_parts: Vec<_> = dir.components().collect();
    let target_parts: Vec<_> = target.components().collect();
    let common = dir_parts
        .iter()
        .zip(&target_parts)
        .take_while(|(a, b)| a == b)
        .count();
    let mut out = std::path::PathBuf::new();
    for _ in common..dir_parts.len() {
        out.push("..");
    }
    for part in &target_parts[common..] {
        out.push(part);
    }
    out
}

/// Every rule the live files cite, and where, as `document · heading`.
///
/// The heading is tracked down the file, and **a heading line is applied before the rule
/// numbers on that same line**: a rule named in a heading belongs under that heading, not
/// under the one above it. The scanner emits the observations in the other order, so this
/// reorders them per line rather than replaying them as they arrive.
fn citations(model: &Model, index_dir: &std::path::Path) -> BTreeMap<Sort, Vec<String>> {
    let mut out: BTreeMap<Sort, BTreeSet<String>> = BTreeMap::new();
    for doc in model.documents() {
        // A markdown link, so a reader follows the row where a renderer shows the page.
        let name = format!(
            "[{}]({})",
            label(doc),
            rel_from(index_dir, &doc.rel).display()
        );
        let mut heading = String::new();
        let mut by_line: BTreeMap<u32, Vec<&Observation>> = BTreeMap::new();
        for l in &doc.observations {
            by_line.entry(l.line).or_default().push(&l.what);
        }
        for (_, observations) in by_line {
            if let Some(Observation::Heading { text, .. }) = observations
                .iter()
                .find(|o| matches!(o, Observation::Heading { .. }))
                .copied()
            {
                // Everything from an em dash onwards is the statement, not the name.
                heading = text.split('—').next().unwrap_or(text).trim().to_string();
            }
            for o in observations {
                if let Observation::RuleToken(rule) = o {
                    let where_ = if heading.is_empty() {
                        name.clone()
                    } else {
                        format!("{name} · {heading}")
                    };
                    out.entry(Sort(rule.clone())).or_default().insert(where_);
                }
            }
        }
    }
    out.into_iter()
        .map(|(k, v)| (k, v.into_iter().collect()))
        .collect()
}

/// A rule number in the order the rule index is generated in: section, then the printed text.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Sort(pub RuleNumber);

impl Ord for Sort {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.0.cmp_index(&other.0)
    }
}

impl PartialOrd for Sort {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

/// `thaum@docs/rules/index.md`: every rule cited, and what depends on it.
///
/// This is what makes a bump actionable — when a rule changes or is renumbered, it says
/// exactly what has to be re-read.
pub fn rule_index(model: &Model, manifest: &Manifest, corpus: &Corpus, pinned: &str) -> String {
    let cites = citations(model, &manifest.rules().dir);
    let (known, unknown): (Vec<_>, Vec<_>) = cites
        .iter()
        .partition(|(Sort(rule), _)| corpus.contains(rule));

    let mut out = String::new();
    out.push_str("# Rule citation index\n\n");
    // The provenance line names the command that regenerates the file, because a generated
    // file a reader cannot regenerate is a file they will edit by hand.
    out.push_str("**Generated — do not edit.** `cargo knowledge index`\n\n");
    out.push_str(
        "Every Comprehensive Rule the live files cite, and where. This is what makes a\n\
         rules bump actionable: when a rule changes or is renumbered, this says exactly what\n\
         depends on it — documents today, code and tests once they exist. The survey is\n\
         excluded, being frozen against its own release.\n\n",
    );
    out.push_str(&format!(
        "Pinned rules release: `{pinned}` · {} rules cited\n\n",
        known.len()
    ));
    out.push_str("| Rule | Cites | Where |\n|---|---|---|\n");
    for (Sort(rule), where_) in &known {
        out.push_str(&format!(
            "| `{rule}` | {} | {} |\n",
            where_.len(),
            where_.join("<br>")
        ));
    }
    if !unknown.is_empty() {
        let names: Vec<String> = unknown
            .iter()
            .map(|(Sort(r), _)| format!("`{r}`"))
            .collect();
        out.push_str(&format!(
            "\n**Not rules in this release** (citation error, or prose that parses as one): {}\n",
            names.join(", ")
        ));
    }
    out
}

/// Greedy wrap on whitespace that never breaks a word, matching the generator being replaced.
pub fn wrap(text: &str, width: usize) -> Vec<String> {
    let mut out = Vec::new();
    let mut line = String::new();
    for word in text.split_whitespace() {
        if !line.is_empty() && line.chars().count() + 1 + word.chars().count() > width {
            out.push(std::mem::take(&mut line));
        }
        if !line.is_empty() {
            line.push(' ');
        }
        line.push_str(word);
    }
    if !line.is_empty() {
        out.push(line);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    // Every fixture is inline: the checker reads no string literal of its own source, per
    // `knowledge#checker-source-literals-are-data`.

    /// A declaration whose rules directory and register directory are one level deep.
    fn declaring() -> Manifest {
        let text = "[project]\nname = \"a-project\"\ncomponents = []\n\n\
             [walk]\nskip-dirs = []\nskip-files = []\n\n\
             [lint]\nexempt-files = []\n\n\
             [rules]\ndir = \"r\"\ntext = \"t\"\nbody-starts-at = 0\n\
             version = \"v\"\npast = \"p\"\nmanifest = \"m\"\n";
        Manifest::parse(std::path::Path::new("/nowhere"), text).expect("a declaration")
    }

    #[test]
    fn a_rule_index_row_links_relative_to_the_index_directory() {
        // A markdown link a renderer follows, with the upward segments the index's own
        // directory requires — legal here because the generated files sit outside the walk
        // and regenerate, so the link cannot go stale.
        let corpus = Corpus::parse("100.1 A mock rule body.\n", 0);
        let doc = "parts/x/doc.md";
        let model = Model::from_documents(vec![(PathBuf::from(doc), "per CR:100.1\n".to_string())]);
        let index = rule_index(&model, &declaring(), &corpus, "20200101");
        let row = format!("[{doc}](../{doc})");
        assert!(index.contains(&row), "{index}");
    }

    #[test]
    fn wrapping_never_breaks_a_word_and_fills_greedily() {
        assert_eq!(wrap("aaa bbb ccc", 7), vec!["aaa bbb", "ccc"]);
        assert_eq!(wrap("averylongword", 4), vec!["averylongword"]);
        assert_eq!(wrap("", 10), Vec::<String>::new());
    }
}
